### ISSUE TITLE
Issue while running the code

### ISSUE THREAD

**Issue by medknecth** [jeffreyrdcs/stock-vcpscreener#1]
Hey Jeffrey,

First of all this is not exactly issue but when I m trying to replicate your code on my local environment I was stuck, did some changes and was able to run it a bit. Now the last I am totally stuck with this errors: 
The selected date is 2022-06-09
Empty DataFrame
Columns: []
Index: []
No update needed
Updating CSV data
No update needed for the database!
2022-06-09 00:00:00
2022-06-10 00:00:00
Working on 2022-06-09
AAPL Empty DataFrame
Columns: [Stock, Index, RS Rating, RS Rating 2, RS Rating 3, 50 Day MA, 150 Day Ma, 200 Day MA, 52 Week Low, 52 week High]
Index: []
Error: 
name 'pd' is not defined
Creating PNG plot for:
No JPG found in input dir. Returning a blank PDF
--------------------------------------------------------------------------------
------------------------ Stock Report for today --------------------------------
--------------------------------------------------------------------------------
Advance / Decline = 0 / 1
New High / New Low = 0 / 0
Gauge = -9894565893.66
Stock above its 20-DMA (%):  0.00
Stock above its 50-DMA (%):  0.00
Stock with 20-DMA > 50-DMA (%):  0.00
Stock with 50-DMA > 200-DMA (%):  0.00
Stock with 50 > 150 > 200-DMA (%):  0.00
Stock with rising 200-DMA (%):  100.00
Number of Stock that fit the conditions: 0
Number of Stock that fit the conditions(%):  0.00
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_832/749149736.py in <module>
    431 
    432     # Generate report
--> 433     svs.generate_report()
    434     svs.generate_dash_csv()
    435 

C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_832/749149736.py in generate_report(self)
    353         out_msg = gen_report_front_page(self.report_dict, stock_namelist, self.cdir_path)
    354         out_status = gen_report_breadth_page(self.report_dict, self.date_study, self.cdir_path)
--> 355         out_status = gen_report_combine(self.cdir_path, self.output_path, self.date_study)
    356 
    357         # Convert report dict to df and update self.dsel_info_name

~\stock-vcpscreener-main\vcp_util\util.py in gen_report_combine(input_dir, output_dir, daily_file_name)
    165     comb.write(outpdf)
    166 
--> 167     os.remove(input_dir+'report_frontpage.pdf')
    168     os.remove(input_dir+'report_breadthpage.pdf')
    169     os.remove(input_dir+'report_outputpage.pdf')

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'stock_vcpscreener//report_frontpage.pdf'

My last goal is to replicate it for Indian Market, I will be grateful for your help and guidance.

**Comment by jeffreyrdcs** [comment]
Hi, sorry for the late reply. I saw that it says` Error: name 'pd' is not defined` in the output. Did you import pandas?
