### ISSUE TITLE
[Resolved!] cannot run it, would you please help me!

### ISSUE THREAD

**Issue by wilsonlam1** [jeffreyrdcs/stock-vcpscreener#3]
I got the error as below:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[16], line 15
     12 import sys
     13 import os
---> 15 from stock_vcpscreener.vcp_util.util import gen_report_front_page, gen_report_output_page, gen_report_combine, \
     16                                             gen_report_breadth_page, \
     17                                             convert_report_dict_to_df, convert_png_jpg, cleanup_dir_jpg_png, \
     18                                             get_last_trade_day
     19 from stock_vcpscreener.vcp_util.stat import compute_rs_rank, compute_rs_rating
     20 from stock_vcpscreener.vcp_util.db import create_index_database, update_index_database, \
     21                                           create_stock_database, update_stock_database, \
     22                                           get_index_lastday, get_stock_data_specific_date

File ~\OneDrive - W\VCP\stock-vcpscreener-main\stock_vcpscreener.py:15
     12 import sys
     13 import os
---> 15 from stock_vcpscreener.vcp_util.util import gen_report_front_page, gen_report_output_page, gen_report_combine, \
     16                                             gen_report_breadth_page, \
     17                                             convert_report_dict_to_df, convert_png_jpg, cleanup_dir_jpg_png, \
     18                                             get_last_trade_day
     19 from stock_vcpscreener.vcp_util.stat import compute_rs_rank, compute_rs_rating
     20 from stock_vcpscreener.vcp_util.db import create_index_database, update_index_database, \
     21                                           create_stock_database, update_stock_database, \
     22                                           get_index_lastday, get_stock_data_specific_date

ModuleNotFoundError: No module named 'stock_vcpscreener.vcp_util'; 'stock_vcpscreener' is not a package

Would anyone can help me?

thanks,
Wilson

**Comment by wilsonlam1** [comment]
I tried to run it on Python 3.12.2 version as below error:

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/1403b279-d570-4630-981e-5b9f2f80c55e)

**Comment by jeffreyrdcs** [comment]
Hi, I think the `distutils` package is no longer included in Python version 3.12.  So to get that you can try
`pip install setuptools` or `pip3 install setuptools`. Let me know if that solves the problem.

**Comment by wilsonlam1** [comment]
Hi Jeffrey,

Thank you so much for your quick reply!

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/ac68ab92-c9b4-491c-b9b3-229fd8f9e621)


It still does not work, your help is much appreciated, thanks!

**Comment by jeffreyrdcs** [comment]
Hi,   No problem, happy to help. It is showing those import error since this repo is written as a module. It was deployed online together with a Dash App. To run it, go outside the main folder (so go to the ./VCP/ dir in your case) and do:

`python -m stock_vcpscreener.stock_vcpscreener`

Make sure to change the name of the module if you rename the directory.

I just pushed the GSPC dataset to the repo as well, so you should see some sort of output without an error telling you to build the database first. Let me know if you can see any output.

I am planning to refactor this codebase at some point later since it is quite old.

**Comment by wilsonlam1** [comment]
Hi Jeffrey,

Thank you so much!!

I have renamed the folder to "stock_vcpscreener", and the files as below:
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/cd946c9b-cd67-4bbf-9d4d-280771d41bf6)

And I run it as below:
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/147d39ce-ab08-4107-b55d-e2ddde599449)


Did I do something wrong of it?

thanks,
Wilson

**Comment by jeffreyrdcs** [comment]
Hi, make sure you have the GSPC_SP500.csv file in the db_yfinance directory.
 
This is the one:  https://github.com/jeffreyrdcs/stock-vcpscreener/blob/main/db_yfinance/GSPC_SP500.csv

You can also build a new one using the `create_index_database` function, but I pushed that file a couple hours ago to the directory so you can use it to see some output for now.

**Comment by wilsonlam1** [comment]
Hi Jeffrey,

Thanks and I just put the GSPC_SP500.csv file in the db_yfinance directory to run it , the result as below:

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/3acf119f-0f91-43e6-91cc-5f9b866df30f)

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/5c288fa1-b633-404f-b8f9-584dbeddb65a)

BTW I have installed all the api (the latest version) on your requirement list as below:

mplfinance
yfinance
seaborn
img2pdf
pandas
matplotlib
numpy
requests
pandas_datareader
fpdf
Pillow
PyPDF2

Thank you for your help in pointing out anything wrong with it.

thanks,
Wilson

**Comment by wilsonlam1** [comment]
Hi Jeffrey,

Something update to you as below:
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/ebcb6d6d-6eda-4891-9ec5-efdbc11cde91)

it seems it cannot download and update the CSV. would you please check it, thanks!

thanks,
Wilson

**Comment by jeffreyrdcs** [comment]
The example in `if __name__ == '__main__'` only try to fetch yesterday's data. So if you run it on Sunday it will try to tell you it is not a valid trade day. You can initiate the StockVCPScreener class with a different date. Just do: `svs = StockVCPScreener(input_date, stock_list)`

**Comment by wilsonlam1** [comment]
Hi,

I just tried to do as below:
`  Specific_date = datetime.today() - timedelta(days=4)
    svs = StockVCPScreener(Specific_date, stock_list)`


![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/f3cccd61-e698-4a0f-8f15-25a9e8d22fa2)

It seems there is another issue.

Thank you very much to check it again, thanks!

thanks,
Wilson

**Comment by jeffreyrdcs** [comment]
datetime.today() gives a datetime.datetime object, but the code takes a datetime.date object. So if you do `datetime.today().date() - timedelta(days=4)` then it will work.

By the way I just started refactoring parts of this repo, hopefully things are clearer that way. If you are interested you can fetch the latest version.

**Comment by wilsonlam1** [comment]
Hi Jeffrey,

I just download it and fetch the latest version, and I also try to allow it to get today's data as below:
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/d406c461-b413-453b-a51b-2971d8a5882c)

Anyway I will try to run it again today later time.

thanks,
Wilson

**Comment by jeffreyrdcs** [comment]
I believe it is because the Update Index step failed, the code sees that the S&P500 index data is not updated.

The error download() got an .... seems to be an issue from the version of pandas_datareader you have. I suspect the newer version no longer have the pause keyword. You can try to remove this pause=1 line inside db.py and try again: https://github.com/jeffreyrdcs/stock-vcpscreener/blob/main/vcp_util/db.py#L88

I also pushed a new version with that line removed.

**Comment by wilsonlam1** [comment]
Hi,

I downloaded your latest version and did it again, this time it shows:

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/3b1cff05-be38-4a56-91f1-5a5ea47fe80c)

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/1142e534-c114-4a91-bfd5-c8c9a814560b)

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/0269c4f9-7483-4876-b6d8-aa53e1357d08)

Please have a look on it, thank you so much for your help!

thanks,
Wilson

**Comment by jeffreyrdcs** [comment]
Some of those are `FutureWarnings` so they are fine, but if you want to get rid of them you can follow the advice to replace those lines with `.iloc[pos]` instead. 

For the seaborn one, I think you haven't install seaborn?  It is a data visualization library and I am only using their styling here for the plots.

**Comment by wilsonlam1** [comment]
I just setup another version of the virtual environment via Anaconda by using Python 3.8 version to do below pip install:

mplfinance==0.12.7a17
yfinance==0.1.63
seaborn==0.11.1
img2pdf==0.4.1
pandas==1.0.3
matplotlib==3.2.1
numpy==1.19.5
requests==2.24.0
pandas_datareader==0.9.0
fpdf==1.7.2
Pillow==8.3.1
PyPDF2==1.26.0

Finally I can run it!! Thank you so much! Here attached 2024-03-21 PDF.
[2024-03-21.pdf](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14718514/2024-03-21.pdf)

@jeffreyrdcs Thank you so much!

**Comment by jeffreyrdcs** [comment]
Great, good to know that helps!
