### ISSUE TITLE
please check if this new error 

### ISSUE THREAD

**Issue by asraghu123** [jeffreyrdcs/stock-vcpscreener#6]
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/6919fa52-5b53-4af2-95fe-de99e5c18b16)

The output file for 21 March is empty 
[selected_stock_2024-03-21.csv](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14717988/selected_stock_2024-03-21.csv)

Also the updates the ticker file in folder  db_yfinance for March 21st (row) was missing for all tickers.  

[AAMC_.csv](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14718352/AAMC_.csv)
[AACQ_.txt](https://github.com/jeffreyrdcs/stock-vcpscreener/files/14718355/AACQ_.txt)
Not sure why the date in this folder is showing 2024.03.23.  The run was done on 22nd March at 0100am CST USA

What changed from yesterday to today ?    
The only change I did was to upgrade the numpy version from what is given in the requirements.txt to numpy==1.22.4 as the old version numpy==1.19.5 had dependencies issues while running dash  app  app.py.  The errors in that was cleared when  I upgraded it to 1.22.4, the command message indicated me to upgrade to a version equal or higher to 1.22.4

**Comment by asraghu123** [comment]
closed by mistake... reopened the issue

**Comment by asraghu123** [comment]
dash appy.py run  error 

![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/76263329/1060a44f-a947-4661-8c32-4fb9707b0c41)

**Comment by wilsonlam1** [comment]
@asraghu123 I got the similar error as below:
![image](https://github.com/jeffreyrdcs/stock-vcpscreener/assets/163280221/09c7fbd3-858a-413b-bdd7-03536476846a)

**Comment by jeffreyrdcs** [comment]
@asraghu123 @wilsonlam1  For the dash app error I just pushed a fix to the stock_vcp_dash repo. It is just an issue due to empty strings. 

Not sure about the first error you posted. It seems to work fine on my side yesterday. It is saying you are trying to access Mar 21st data without updating.  May be yfinance has not been updated yet or something?

**Comment by asraghu123** [comment]
The first error resolved after I deleted the entire db_yfinance folder data and recreated it from scratch.  I somehow think  updating from US using uk.yahoo and timezones are playing some role in the update operation issues.   Will keep a watch on this for some time

**Comment by jeffreyrdcs** [comment]
I see, thanks. If that happen again please let me know.

**Comment by asraghu123** [comment]
I had to manually change the date in last update. Dat file  to make it
work.
